{% set version = "2020.7" %}

package:
  name: gromacs
  version: {{ version }}

build:
# switch to number 100 for mpi version
# 1: rebuild with plumed 2.8
  number: 1

source:
  url: http://ftp.gromacs.org/pub/gromacs/gromacs-{{ version }}.tar.gz
  sha256: 744158d8f61b0d36ffe89ec934519b7e0981a7af438897740160da648d36c2f0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils     # [not (osx and arm64)]
    - cmake
    - llvm-openmp  # [osx]
    - python
  host:
    - openmpi
    - fftw
    - libhwloc 1.* # [not (osx and arm64)]
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - plumed
  run:
    - openmpi
    - fftw
    - libhwloc 1.* # [not (osx and arm64)]
    - llvm-openmp  # [osx]
    - plumed >=2

test:
  commands:
    - gmx_mpi -version
    - gmx_mpi mdrun -h | grep plumed

about:
  home: http://www.gromacs.org/
  license: GNU Lesser General Public License (LGPL)
  summary: GROMACS is a versatile package to perform molecular dynamics.
