name: CI

on:
  push:
  pull_request:

jobs:
  conda:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install conda
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/conda-ci/master/conda-ci
        source ./conda-ci install
        source ./conda-ci install-conda-build
    - name: Build
      run: |
        export MAKEFLAGS=-j3
        conda create --name build
        source activate build
        conda-build -m .github/conda_build_config.yaml -c conda-forge plumed
        conda-build -m .github/conda_build_config.yaml -c conda-forge py-plumed
        conda-build -m .github/conda_build_config.yaml -c conda-forge gromacs
        conda-build -m .github/conda_build_config.yaml -c conda-forge lammps
    - name: Deploy
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
      run: |
        source activate base # needed to have correct CONDA_PREFIX
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u plumed -l tutorials-2024 $CONDA_PREFIX/conda-bld/*/lammps*.tar.bz2 --force
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u plumed -l tutorials-2024 $CONDA_PREFIX/conda-bld/*/plumed*.tar.bz2 --force
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u plumed -l tutorials-2024 $CONDA_PREFIX/conda-bld/*/py-plumed*.tar.bz2 --force
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u plumed -l tutorials-2024 $CONDA_PREFIX/conda-bld/*/gromacs*.tar.bz2 --force
    - name: Test
      run: |
        conda create --name plumed-masterclass
        source activate plumed-masterclass
        conda install -y -c conda-forge plumed py-plumed numpy pandas matplotlib notebook mdtraj mdanalysis git
        # check if python module is working
        python -c "import plumed; p=plumed.Plumed(); print(p)"
        # first install serial gromacs
        conda install -y --strict-channel-priority -c plumed/label/masterclass  -c conda-forge gromacs
        # then replace with parallel gromacs and plumed
        conda install -y --strict-channel-priority -c plumed/label/tutorials-2024 -c conda-forge plumed
        conda install -y --strict-channel-priority -c plumed/label/tutorials-2024 -c conda-forge gromacs
        # check if python module is working
        python -c "import plumed; p=plumed.Plumed(); print(p)"
        cd test
        gmx_mpi mdrun -s topolA.tpr -plumed plumed.dat -nsteps 1000
        cat colvar.dat
        mpiexec --oversubscribe -np 3 gmx_mpi mdrun -multidir dir? -plumed plumed.dat
        cat dir*/colvar*.dat
        # install lammps
        cd -
        conda install -y --strict-channel-priority -c plumed/label/tutorial-2024 -c conda-forge plumed lammps
        cd test-lammps
        mpiexec lmp -in start.lmp
        cat COLVAR
